2024-08-08 15:25:47.348103-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "VETERINARIOS" not found (this database is empty); SQL statement:
INSERT INTO VETERINARIOS VALUES (DEFAULT,?,?,?,?) [42104-230]
2024-08-08 15:25:47.918108-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "VETERINARIOS" not found (this database is empty); SQL statement:
SELECT * FROM VETERINARIOS [42104-230]
2024-08-08 15:28:44.733985-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "VETERINARIOS" not found (this database is empty); SQL statement:
INSERT INTO VETERINARIOS VALUES (DEFAULT,?,?,?,?) [42104-230]
2024-08-08 15:28:45.436990-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "VETERINARIOS" not found (this database is empty); SQL statement:
SELECT * FROM VETERINARIOS [42104-230]
2024-08-08 15:34:32.956574-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "VETERINARIOS" not found (this database is empty); SQL statement:
INSERT INTO VETERINARIOS VALUES (DEFAULT,?,?,?,?) [42104-230]
2024-08-08 15:34:33.608581-06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "VETERINARIOS" not found (this database is empty); SQL statement:
SELECT * FROM VETERINARIOS [42104-230]
2024-08-09 19:54:54.995050-05:00 database: wrong user or password; user: "SA"
org.h2.message.DbException: Nombre de usuario ó password incorrecto
Wrong user name or password [28000-230]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.engine.Engine.openSession(Engine.java:154)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:344)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:291)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:811)
	at org.h2.server.web.WebApp.login(WebApp.java:1038)
	at org.h2.server.web.WebApp.process(WebApp.java:226)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:176)
	at org.h2.server.web.WebThread.process(WebThread.java:154)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Nombre de usuario ó password incorrecto
Wrong user name or password [28000-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:522)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 16 more
2024-08-09 19:55:26.169091-05:00 jdbc[3]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-230]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:217)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:134)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:291)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:811)
	at org.h2.server.web.WebApp.login(WebApp.java:1038)
	at org.h2.server.web.WebApp.process(WebApp.java:226)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:176)
	at org.h2.server.web.WebThread.process(WebThread.java:154)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 13 more
